name: helmtest
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6 
  - cudatoolkit=11.1
  - pytorch=1.9.0
  - pytorch-lightning=1.4.0
  - matplotlib
  - scipy
prefix: home/xchleb07/anaconda3/envs/helmtest
