name: helmtest
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.10.0=py37hc8dfbb8_1
  - aiohttp=3.7.2=py37h8f50634_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.10.14=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.2=py37hff6837a_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=0.8.4=py_0
  - future=0.18.2=py37hc8dfbb8_2
  - glib=2.66.1=h92f7085_0
  - google-auth=1.23.0=pyhd8ed1ab_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.33.2=py37haffed2e_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.0=py37h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.3=pyh9f0ad1d_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - multidict=4.7.5=py37h8f50634_2
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=py37hfd86e86_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - packaging=20.4=pyh9f0ad1d_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.2.4=py37_0
  - protobuf=3.13.0.1=py37h3340039_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - pytorch-lightning=1.0.4=py_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.3.0=py_0
  - tensorboard-plugin-wit=1.7.0=pyh9f0ad1d_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.1=py37_cu102
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.51.0=pyh9f0ad1d_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.2=py37h8f50634_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/astanziola/anaconda3/envs/helmtest
